version: "3.9"

services:
  llm-router:
    container_name: llm-router
    build: .
    env_file:
      - .env
    networks:
      - internal
      - proxy-network
    depends_on:
      - llm-router-redis
    expose:
      - "8000"

  llm-router-redis:
    image: redis:7
    volumes:
      - $HOME/app_data/llm-router/redis:/data
    networks:
      - internal

networks:
  internal:
    driver: bridge

  proxy-network:
    external: true
