version: "3.9"

services:
  llm-router:
    build: .
    env_file:
      - .env
    networks:
      - internal
    depends_on:
      - llm-router-redis
    ports:
      - "9632:8000"

  llm-router-redis:
    image: redis:7
    volumes:
      - $HOME/app_data/llm-router/redis:/data
    networks:
      - internal

networks:
  internal:
    driver: bridge